<?php
/**
 * Configuration file generated by ZF Apigility Admin
 *
 * The previous config file has been stored in ./config/modules.config.old
 */
return array(
    'Zend\\InputFilter',
    'Zend\\Filter',
    'Zend\\Hydrator',
    'Zend\\I18n',
    'Zend\\Paginator',
    'Zend\\Navigation',
    'Zend\\Form',
    'Zend\\Db',
    'Zend\\Router',
    'Zend\\Validator',
    'ZendDeveloperTools',
    'ZF\\Versioning',
    'ZF\\ApiProblem',
    'ZF\\ContentNegotiation',
    'ZF\\Rpc',
    'ZF\\MvcAuth',
    'ZF\\Hal',
    'ZF\\Rest',
    'ZF\\ContentValidation',
    'ZF\\Apigility',
    'ZF\\Configuration',
    'ZF\\Apigility\\Admin',
    'ZF\\Apigility',
    'ZF\\Apigility\\Provider',
    'Application',
    'Album',
    'Albumsdb',
);
